name: calculator
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  math_expressions: ^2.6.0



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

dependency_overrides:
  characters: ^1.3.1
  collection: ^1.19.1
  material_color_utilities: ^0.12.0
  meta: ^1.16.0
  async: ^2.12.0
  boolean_selector: ^2.1.2
  clock: ^1.1.2
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  leak_tracker_flutter_testing: ^3.0.9
  lints: ^5.1.0
  matcher: ^0.12.17
  path: ^1.9.1
  stack_trace: ^1.12.0
  string_scanner: ^1.4.0
  test_api: ^0.7.3
  vm_service: ^14.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/


  # Uncomment and configure the following lines if you plan to add assets to your project.
  # assets:
  #   - images/
  #   - assets/
